[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "26"

version-androidx-activityCompose = "1.13.0"
version-gradle-pdf = "4.0.5"
version-jetbrains-kotlin = "1.11.1"
version-junit = "6.1.2"
version-kermit = "2.1.0"
version-kotlin = "2.3.20" # DO NOT UPGRADE FOR NOW
version-kotlinx-coroutines = "1.11.0"
version-ksoup = "0.2.6"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "version-androidx-activityCompose" }
compose-components = { module = "org.jetbrains.compose.components:components-resources", version.ref = "version-jetbrains-kotlin" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "version-jetbrains-kotlin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "version-jetbrains-kotlin" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "version-junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "version-junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "version-junit" }
kermit = { module = "co.touchlab:kermit", version.ref = "version-kermit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "version-kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "version-kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "version-kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "version-kotlinx-coroutines" }
ksoup-core = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "version-ksoup" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "version-kotlin" }
gradle-pdf = { id = "org.asciidoctor.jvm.pdf", version.ref = "version-gradle-pdf" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "version-jetbrains-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "version-kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "version-kotlin" }
